### ISSUE TITLE
Client to client outgoing call fails to connect randomly

### ISSUE THREAD

**Issue by aksthelion** [twilio/voice-quickstart-swift#197]
### Description

Client to client outgoing call fails first time after install. On iPhone 5S it fails more often than on iPhone 7s Plus. When tapped on call button callKit is fired in the background but nothing happens.

### Steps to Reproduce

1. Run it on iPhone 7S and initiate client to client call

#### Expected Behavior

It should either connect or return failure and kill callKit.

#### Actual Behavior

Neither connects nor kills callKit. callKit keeps running in the background

#### Reproduces How Often

Over 90% of time on iPhone 5s and first time on iPhone 7 Plus

#### Logs

```
StartCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 7.)
```
error 7 is CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached

#### Voice iOS SDK

2.0.0-beta13 via CocoaPods

#### iOS Version

12.1.1

#### iOS Device

iPhone 5s, iPhone 7 Plus

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

Thanks for reporting the issue. Are you always getting the `requesttransaction error 7` message when the error happens?

**Comment by aksthelion** [comment]
Hello, Yes error 7 is the error it throws when this issue happens.

**Comment by aksthelion** [comment]
I've been chasing this issue since long time, had a ticket on twilio as well also tried forums etc but couldn't get any solution. The only thing I can think of is that iPhone 5s is a bit of slow device which may be causing this issue to happen more frequently, however it may be just my imagination.

**Comment by bchen-twilio** [comment]
Cool.
From what error code is suggesting (`CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached`) it seems the error is happening after a couple of calls due to the sample failing to report call ended to the CallKit.
Definitely happy to try the steps and fix the issue but would be great if you can help us narrow down the exact steps to get to this bug.

Thanks
-bobie

**Comment by aksthelion** [comment]
Sure, let me know instructions. Here is interesting thing, if call fails very first time then shouldn't it be reporting some error and kill callKit, in this way we would at least know what is happening? Anyways let me know how do we go about debugging it.

**Comment by aksthelion** [comment]
Hello, any update on this issue?

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

Sorry for my lack of responsiveness.
We have recently added some updates (#200, #201) to the sample app which should improve the stability of CallKit integration. I tried the combination of multiple calls, including outgoing and incoming and reject, and I haven't been able to see the same CallKit failure that used to happen. Please check out the updates and let me know if the updates fix the issue you are seeing.

I apologize again for the delay of responding back to you.

best,
-bobie

**Comment by bchen-twilio** [comment]
Closing this issue assuming the original issue was resolved by the updates of the sample app. Please reopen or create a new issue.
Thanks!

**Comment by aksthelion** [comment]
I already have latest code. It doesn't resolve the issue. Not sure why it's so hard for anyone to understand this simple problem. In my case call doesn't start but callkit UI is fired. **If call is not connected then whatever you all keep saying all the time to fix doesn't work.**

**1) Callkit UI is started 
2) Call is not connected. There is not call in progress, there is no UI there is nothing related with call.**
