### ISSUE TITLE
Outgoing call doesn't disconnect after it Declined on the other side

### ISSUE THREAD

**Issue by AlexSeverinov** [twilio/voice-quickstart-swift#268]
### Description

Outgoing call doesn't disconnect after it Declined on the other side

### Steps to Reproduce

1. Make outgoing call
2. Decline it on other side (not Accept it)
3. Call not cancelled still ringing

#### Code

Reproduced in `voice-quickstart-swift` project

#### Expected Behavior

Notify about the call is rejected 

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

100%

#### Voice iOS SDK

5.0.0

#### Xcode

10.2.1
11.1

#### iOS Version

12.4.1
13.1

#### iOS Device

iPhone 7

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Thanks for reaching out.
I've tried the Swift quickstart but was able to get the disconnected callback on the caller side when the call was rejected on the other side. Can you provide a Twilio Call SID and the SDK log of caller/callee so we can investigate if there is any potential issue?
I am also wondering about the configuration of the callee: 
- Is the callee also an iOS client?
- Is the app in the background or is the device locked when rejecting the call? (I tried this as well and it worked)

-bobie

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 

[IMG_0001.mov.zip](https://github.com/twilio/voice-quickstart-swift/files/3683229/IMG_0001.mov.zip)

2019-10-02 23:36:52.322338+0300 SwiftVoiceQuickstart[1734:253090] callDidStartRinging:
2019-10-02 23:36:53.808647+0300 SwiftVoiceQuickstart[1734:253090] callDidConnect:
2019-10-02 23:36:53.875170+0300 SwiftVoiceQuickstart[1734:253090] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2019-10-02 23:36:57.012047+0300 SwiftVoiceQuickstart[1734:253690] [] tcp_input [C4.1:3] flags=[R] seq=2296079455, ack=0, win=0 state=LAST_ACK rcv_nxt=2296079456, snd_una=3277391109
2019-10-02 23:36:57.012253+0300 SwiftVoiceQuickstart[1734:253690] [] tcp_input [C4.1:3] flags=[R] seq=2296079456, ack=0, win=0 state=LAST_ACK rcv_nxt=2296079456, snd_una=3277391109
2019-10-02 23:36:57.012457+0300 SwiftVoiceQuickstart[1734:253690] [] tcp_input [C4.1:3] flags=[R] seq=2296079456, ack=0, win=0 state=CLOSED rcv_nxt=2296079456, snd_una=3277391109
2019-10-02 23:37:32.409878+0300 SwiftVoiceQuickstart[1734:253584] EndCallAction transaction request successful
2019-10-02 23:37:32.412465+0300 SwiftVoiceQuickstart[1734:253090] provider:performEndCallAction:
2019-10-02 23:37:33.057712+0300 SwiftVoiceQuickstart[1734:253090] provider:didDeactivateAudioSession:
2019-10-02 23:37:33.663128+0300 SwiftVoiceQuickstart[1734:253090] Call disconnected
2019-10-02 23:38:10.713020+0300 SwiftVoiceQuickstart[1734:253791] StartCallAction transaction request successful
2019-10-02 23:38:10.718681+0300 SwiftVoiceQuickstart[1734:253090] provider:performStartCallAction:
2019-10-02 23:38:10.876887+0300 SwiftVoiceQuickstart[1734:253090] provider:didActivateAudioSession:
2019-10-02 23:38:12.591845+0300 SwiftVoiceQuickstart[1734:253090] callDidStartRinging:
2019-10-02 23:38:13.574851+0300 SwiftVoiceQuickstart[1734:253090] callDidConnect:
2019-10-02 23:38:13.853781+0300 SwiftVoiceQuickstart[1734:253090] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2019-10-02 23:38:28.018924+0300 SwiftVoiceQuickstart[1734:254067] EndCallAction transaction request successful
2019-10-02 23:38:28.020798+0300 SwiftVoiceQuickstart[1734:253090] provider:performEndCallAction:
2019-10-02 23:38:28.713788+0300 SwiftVoiceQuickstart[1734:253090] provider:didDeactivateAudioSession:
2019-10-02 23:38:29.277191+0300 SwiftVoiceQuickstart[1734:253090] Call disconnected
2019-10-02 23:38:32.092878+0300 SwiftVoiceQuickstart[1734:254149] [] tcp_input [C11.1:3] flags=[R] seq=3109961271, ack=0, win=0 state=LAST_ACK rcv_nxt=3109961271, snd_una=4157556190
2019-10-02 23:38:32.095163+0300 SwiftVoiceQuickstart[1734:254149] [] tcp_input [C11.1:3] flags=[R] seq=3109961271, ack=0, win=0 state=CLOSED rcv_nxt=3109961271, snd_una=4157556190
2019-10-02 23:38:42.722041+0300 SwiftVoiceQuickstart[1734:254067] StartCallAction transaction request successful
2019-10-02 23:38:42.729006+0300 SwiftVoiceQuickstart[1734:253090] provider:performStartCallAction:
2019-10-02 23:38:42.858426+0300 SwiftVoiceQuickstart[1734:253090] provider:didActivateAudioSession:
2019-10-02 23:38:44.700863+0300 SwiftVoiceQuickstart[1734:253090] callDidStartRinging:
2019-10-02 23:38:45.483060+0300 SwiftVoiceQuickstart[1734:253090] callDidConnect:
2019-10-02 23:38:45.741076+0300 SwiftVoiceQuickstart[1734:253090] AVAudioSession setAggregatedIOPreference:error: Error Domain=NSOSStatusErrorDomain Code=560030580 "(null)"
2019-10-02 23:39:04.121052+0300 SwiftVoiceQuickstart[1734:254067] [] tcp_input [C16.1:3] flags=[R] seq=107801159, ack=0, win=0 state=LAST_ACK rcv_nxt=107801159, snd_una=2488153688
2019-10-02 23:39:04.122094+0300 SwiftVoiceQuickstart[1734:254067] [] tcp_input [C16.1:3] flags=[R] seq=107801159, ack=0, win=0 state=CLOSED rcv_nxt=107801159, snd_una=2488153688
2019-10-02 23:39:21.731473+0300 SwiftVoiceQuickstart[1734:254112] EndCallAction transaction request successful
2019-10-02 23:39:21.732208+0300 SwiftVoiceQuickstart[1734:253090] provider:performEndCallAction:
2019-10-02 23:39:22.354442+0300 SwiftVoiceQuickstart[1734:253090] provider:didDeactivateAudioSession:
2019-10-02 23:39:22.991400+0300 SwiftVoiceQuickstart[1734:253090] Call disconnected

**Comment by AlexSeverinov** [comment]
Twilio Call SID: CAed1608b814d65ef536baa5ce0ecbc6b2

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Thanks for providing the SDK log and from the log it seems the call was ended (with CallKit) properly and the `call:didDisconnectWithError:` callback was received on the application's side. 

-bobie

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 
 `call:didDisconnectWithError:` it's fired when I stop a call. Video exactly for this logs.
Thanks

**Comment by AlexSeverinov** [comment]
@bchen-twilio See time in logs

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Sorry I missed the video. I just realized the original scenario was to make an outgoing call to a PSTN number. Any chance the call was sent to a voice mail when the callee declined the call? (this happened to me when I tried the same case and i can hear the voicemail prompt from the phone speaker going on for a while before it ended).

-bobie

**Comment by AlexSeverinov** [comment]
Hi Bodie
Not clear your question.
In other words `Reject` scenario looks like if callee not answer to a call.

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

When you decline the call on the PSTN side, do you hear voicemail prompt on the caller's side (mobile client)?

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 
In the moment when I decline the call I didn't  hear voicemail prompt.

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Did you hear a ringing tone on the caller's side and did the ringtone stop when the other side declined the call?

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 
I heard ringing tone on the caller side and it didn't stop when I decline it on the other side.
It looks like `not answered` on caller side. Video clearly explain this case.

**Comment by bchen-twilio** [comment]
I see @AlexSeverinov. I'll reach out to our backend expert and see if they can figure out the reason why the caller was not disconnected immediately when the call was declined. Will keep you updated.

-bobie

**Comment by AlexSeverinov** [comment]
Thanks @bchen-twilio. I'll wait for your answer.

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Our backend expert checked the Call SID and cam back with some findings: the called side wasn’t actually declined from Twilio's perspective, the call got connected from packet capture data. We think it went to the user’s voicemail or something when the called user declined the call from their phone.

Can you help try calling a different number or a mobile client and see if the callee can get the disconnected callback when the call is rejected?

Thanks,
-bobie

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 

Thanks for the reply.

When I do a call to cell phone it works properly.
But call from iOS to web has issue that I describe above. (both platform use Twilio SDK )
 
![Screen Shot 2019-10-04 at 12 46 27 AM](https://user-images.githubusercontent.com/3671476/66166966-77484b00-e641-11e9-8862-4c2546b4c212.png)

SID's are in order as on the screenshot:

CALL SID
CA19a05935eec9784ce6768184d3b6e01f

CALL SID
CAfd1cb30318b98ee74aa5361869fb93f1

CALL SID
CA8ce42e7b1eb786897343ea876d67a510

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

The original scenario where you were observing no-disconnect problem on the caller side was a call made from iOS client to an PSTN cell number. Can you clarify the exact case and the steps where the issue is happening?

Thanks,
-bobie

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 

1. I make the call from iOS client to web client (both platform use Twilio SDK )
2. On web client I Decline the call.
3. On iOS client I still hear a ringing tone

**Comment by bchen-twilio** [comment]
Hi @AlexSeverinov 

Can you provide the Call SID of the above scenario?
I noticed in the Call SIDs you provided, there was a second part TwiML response triggered by the `action` URL in the `\<Dial\>` verb of the first part (for example for parent call of CA19a05935eec9784ce6768184d3b6e01f). There is also a `\<Record\>` verb in the response, which might be the reason that the call did not disconnect immediately after being rejected.

Thanks,
-bobie

**Comment by AlexSeverinov** [comment]
Hi @bchen-twilio 

![Screen Shot 2019-10-08 at 12 42 16 PM](https://user-images.githubusercontent.com/3671476/66385819-cd164d80-e9c9-11e9-9890-f36fa58d19cd.png)

SID's are in order as on the screenshot:

CALL SID
CA19a05935eec9784ce6768184d3b6e01f

CALL SID
CAfd1cb30318b98ee74aa5361869fb93f1

CALL SID
CA8ce42e7b1eb786897343ea876d67a510

CALL SID
CAf5262264dc4007620bffdce7ff93e0fc

**Comment by bchen-twilio** [comment]
HI @AlexSeverinov 

I saw the ticket has been closed but just would like to check in and make sure that the original issue you were experiencing has been resolved. Feel free to reach out to us if you run into any issue using the Voice SDK.

Thank you,
-bobie

**Comment by stephanrotolante** [comment]
This is still an issue... I am using the nodeJS SDK. When the outbound calls are made I decline them, but the phone will ring again (many seconds after) even though I declined the call. My current work around for this is using a setTimeOut and manually cancel the call with the callSID after N amount of seconds

**Comment by bobiechen-twilio** [comment]
Hi @stephanrotolante 

Are you using the `call.disconnect()` (caller side) or the `callInvite.reject()` (callee side) method by declining the call? We can use a Twilio Call SID and the SDK log (TRACE level) to check if everything works as expected.

Thanks,
-bobie

**Comment by stephanrotolante** [comment]
@bobiechen-twilio I'm not using either of those. FYI I am not outbound dialing another twilio number, I am dialing a personal cellphone

**Comment by bobiechen-twilio** [comment]
@stephanrotolante 

Could you provide more detail about how the call was made and the call parties (cell phone, mobile client, etc.)? Also a Call SID would be great if there is a Programmable Voice call in the call flow.

**Comment by stephanrotolante** [comment]
I am using the client api with a mix of xml twiml responses. Basically the whole flow is:

Person 1 calls our twilio number -> Person 1 gets put into empty conference -> Out bound call is made to Person 2 (using the client api) -> use status call back events to track certain actions made by Person 2 -> put Person 2 in conference with Person 1 based off certain actions 

I hope this kind of makes sense... I am using the CallBackStatusEvents to keep track if the call is canceled or is in a ringing state. There isn't a call back status event I see that fires off if someone declines the call. Twilio will keep trying to ring even after the call is declined, that is way I am having to manually update the call to a canceled state after an N number of seconds

**Comment by bobiechen-twilio** [comment]
Hi @stephanrotolante 

Do you have any Twilio Call SID of the conference calls?
If I am understanding correctly, are you having trouble getting the correct status callback when a conference participant rejects the call?

Another question: is there any iOS or Android SDK client as the conference participant you are trying to call or are they phone numbers?

**Comment by stephanrotolante** [comment]
@bobiechen-twilio 
Yes, but they technically aren't a conference participant at that point in time

**Comment by bobiechen-twilio** [comment]
Thanks for the updates @stephanrotolante.
For questions about the Node library, it would be better answered in the [Twilio Node repo](https://github.com/twilio/twilio-node). I would also encourage you to use [Twilio Support](https://support.twilio.com/hc/en-us) for the Conference usage.
